[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."core-blocks"]
  included_files = ["node_modules/@wordpress/block-library/src/**"]
